
esphome:
  name: estanque
  friendly_name: estanque

esp32:
  board: ttgo-t1
  framework:
    type: arduino
    version: 3.1.3

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "PRLgpmHE462vdbUl8RhYa7KnaBg4s0h60t42NWILxyM="

ota:
  - platform: esphome
    password: "4b0bba8dd88e8041dfee0eb8487610ff"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Estanque Fallback Hotspot"
    password: "FM7I4p2AbJ5o"

captive_portal:

external_components:
  - source:
      type: git
      url: file:///external_components/water_magic
      ref: main
    refresh: 1s
    components: [ water_distance_dual ]

sensor:
  # - platform: water_magic
  #  id: goo

  - platform: water_distance_dual
    distance:
      name: "Distancia"
    level:
      name: "Nivel"
    update_interval: 600s
